version: '3'
services:
  dbt-bq-dtc:
    build:
      context: .
      target: dbt-bigquery
    image: dbt/bigquery
    volumes:
      - .:/usr/app
      - /Users/julien.muller/Documents/de-zoomcamp/project/dbt/.dbt:/root/.dbt/
      - ~/Documents/secrets/personal-gcp.json/eighth-veld-411323-8a0d542a0598.json:/.google/credentials/google_credentials.json
    network_mode: host