version: 2

sources:
  - name: staging
    database: eighth-veld-411323
    schema: taxi_trips_all
    
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata